services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "3000:3000"
    volumes:
      - ".:/src"
      - bundle_cache:/usr/local/bundle
      - sqlite_data:/src/db
      - rails_tmp:/src/tmp
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
    driver: local
  sqlite_data:
    driver: local
  rails_tmp:
    driver: local
